# Generated by Django 5.2.6 on 2025-09-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_suscripciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suscripcion',
            old_name='activo',
            new_name='activa',
        ),
    ]
