# Generated by Django 5.2 on 2025-09-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_suscripciones', '0002_rename_activo_suscripcion_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='email_notificaciones',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
